services:
  prometheus:
    image: lucasmgpy/devlukeops-prometheus:latest
    build:
      context: ./monitoring/prometheus
      dockerfile: Dockerfile
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus  # Volume para dados do Prometheus
  grafana:
    image: lucasmgpy/devlukeops-grafana:latest
    build:
      context: ./monitoring/grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana  # Volume para dados do Grafana
  app:
    image: lucasmgpy/devlukeops-app:latest
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5110:5110"
    volumes:
      - app-data:/app  # Volume para persistir o banco de dados SQLite

volumes:
  prometheus-data:
  grafana-data:
  app-data: