services:
  prometheus:
    build:
      context: ./monitoring/prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    build:
      context: ./monitoring/grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5110:5110"
